source "https://rubygems.org"

gem 'rspec', "~> 3.1.0"
gem 'byebug'

# %w[rspec rspec-core rspec-expectations rspec-mocks rspec-support].each do |lib|
#   gem lib, :git => "https://github.com/rspec/#{lib}.git", :branch => 'master'
# end
